import { spawn } from 'child_process';
import { mkdir, readFile, writeFile } from 'fs/promises';
import { dirname, resolve } from 'path';

import { safOpenApiSpecs, type SafOpenApiSpecConfig } from '../src/saf/specs';

const yaml = require('js-yaml') as {
  load: (value: string) => unknown;
};

const rootDir = resolve(__dirname, '..');
const operationRegistryPath = resolve(rootDir, 'src/saf/generated/apiOperationRegistry.ts');
const httpMethods = ['get', 'post', 'put', 'patch', 'delete'] as const;

type HttpMethod = (typeof httpMethods)[number];

type OpenApiDocument = {
  paths?: Record<string, Partial<Record<HttpMethod, OpenApiOperation>>>;
};

type OpenApiOperation = {
  operationId?: string;
  summary?: string;
};

type OperationMetadata = {
  id: string;
  name: string;
  method: Uppercase<HttpMethod>;
  path: string;
  operationId: string;
};

async function generateTypes(spec: SafOpenApiSpecConfig): Promise<void> {
  const specPath = resolve(rootDir, spec.outputPath);
  const generatedTypesPath = resolve(rootDir, spec.generatedTypesPath);

  await mkdir(dirname(generatedTypesPath), { recursive: true });

  console.log(`Generating ${spec.name}`);
  console.log(`Spec Path: ${spec.outputPath}`);
  console.log(`Types Path: ${spec.generatedTypesPath}`);

  await runOpenApiTypescript(specPath, generatedTypesPath);
}

async function generateOperationRegistry(specs: SafOpenApiSpecConfig[]): Promise<void> {
  const registry: Record<string, OperationMetadata[]> = {};

  for (const spec of specs) {
    const specPath = resolve(rootDir, spec.outputPath);
    const document = yaml.load(await readFile(specPath, 'utf8')) as OpenApiDocument;

    registry[spec.id] = extractOperations(document);
  }

  await mkdir(dirname(operationRegistryPath), { recursive: true });
  await writeFile(operationRegistryPath, renderOperationRegistry(registry), 'utf8');

  console.log(`Operation Registry: ${operationRegistryPath.replace(`${rootDir}/`, '')}`);
}

function extractOperations(document: OpenApiDocument): OperationMetadata[] {
  return Object.entries(document.paths ?? {}).flatMap(([path, pathItem]) =>
    httpMethods.flatMap((method) => {
      const operation = pathItem?.[method];
      const operationId = operation?.operationId;

      if (!operationId) {
        return [];
      }

      return [
        {
          id: operationId,
          name: operation.summary?.trim() || operationId,
          method: method.toUpperCase() as Uppercase<HttpMethod>,
          path,
          operationId,
        },
      ];
    }),
  );
}

function renderOperationRegistry(registry: Record<string, OperationMetadata[]>): string {
  return `/* eslint-disable */
/**
 * This file is auto-generated by scripts/generate-api.ts.
 * Do not edit manually.
 */

import type { SafApiOperationMetadata } from '../apiOperationMetadata';

export const apiOperationRegistry: Record<string, SafApiOperationMetadata[]> = ${JSON.stringify(registry, null, 2)};
`;
}

function runOpenApiTypescript(specPath: string, generatedTypesPath: string): Promise<void> {
  return new Promise((resolvePromise, reject) => {
    const child = spawn(
      'openapi-typescript',
      [specPath, '-o', generatedTypesPath],
      {
        cwd: rootDir,
        shell: process.platform === 'win32',
        stdio: 'inherit',
      },
    );

    child.on('error', reject);
    child.on('close', (code) => {
      if (code === 0) {
        resolvePromise();
        return;
      }

      reject(new Error(`openapi-typescript exited with code ${code ?? 'unknown'}.`));
    });
  });
}

async function main() {
  for (const spec of safOpenApiSpecs) {
    await generateTypes(spec);
  }

  await generateOperationRegistry(safOpenApiSpecs);
}

void main().catch((error) => {
  console.error(error instanceof Error ? error.message : error);
  process.exitCode = 1;
});
